# Site settings
title: Math, Music, and Mac & Cheese
description: > # this means to ignore newlines until "baseurl:"
  A blog about math, LaTeX, programming, electronics,
  music, books, food, and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  robbystk

# Build settings
markdown:       kramdown
highlighter:    rouge
